_target_: trainer.base.BaseTrainer
max_steps: 10000
do_normal: True
do_frame_active: True
do_sample_active: False
bounds_method: "pc"
max_time_since_kf: 5.
window_size: 5
window_limit_size: 2
n_rays_train: 200
min_depth_train: 0.07
n_strat_samples_train: 19
n_surf_samples_train: 8
strat_bin_len_train: null
surf_std_train: 0.1
dist_behind_surf_train: 0.1
n_rays_check: 400
min_depth_check: 0.07
n_strat_samples_check: 19
n_surf_samples_check: 8
strat_bin_len_check: null
surf_std_check: 0.1
dist_behind_surf_check: 0.8
kf_dist_th: 0.1
kf_pixel_ratio: 0.65
trunc_distance: 0.29365022
trunc_weight: 5.3834402
grad_weight: 0.018
eik_apply_dist: 0.1
eik_weight: 0.268
loss_approx_factor: 8
iters_start: 200
iters_per_frame: 10
iters_per_kf: 60
noise_std: 0.25
noise_frame: 0.04 
noise_kf: 0.08

