_target_: dataset.replica.ReplicaDataset
root_dir: /media/SSD/jingyi/iSDF/data/seqs/apt_3_nav
K_file: K_file.txt
T_file: traj.txt 

rgb_transform:
  _target_: utilities.transforms.image_transforms.Image_Transforms
depth_transform: 
  _target_: utilities.transforms.depth_transforms.Depth_Transforms
  scale: 3276.75
  max_depth: 12

scene_folder: /media/SSD/jingyi/iSDF/data/gt_sdfs/apt_3/




